django_poke/django_poke/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^pokes/', include('pokes.urls', namespace="pokes")),
    url(r'^admin/', include(admin.site.urls)),
)

django_poke/pokes/urls.py
from django.conf.urls import patterns, url

from pokes import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^user/new/$', views.NewUserView.as_view(), name='new_user'),
    url(r'^user/add/$', views.add_user, name='add_user'),
    url(r'^(?P<user_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<user_id>\d+)/poke/$', views.create_poke, name='create_poke'),
)

django_poke/pokes/models.py
import datetime

from django.db import models
from django.utils import timezone

class User(models.Model):
  username = models.CharField(max_length=200)

  def __unicode__(self):
    return self.username

class Poke(models.Model):
  send_user = models.ForeignKey(User, related_name="poker")
  receive_user = models.ForeignKey(User, related_name="pokee")
  poke_date = models.DateTimeField('date poked')

  def __unicode__(self):
    return "Poke from {0} to {1}".format(self.send_user.username, self.receive_user.username)

  # Really just for fun since we can
  def was_poked_recently(self):
    now = timezone.now()
    return now - datetime.timedelta(days=1) <= self.poke_date <= now

  was_poked_recently.admin_order_field = 'poke_date'
  was_poked_recently.boolean = True
  was_poked_recently.short_description = 'Poked recently?'

django_poke/pokes/views.py
from django.shortcuts import get_object_or_404, render, get_list_or_404
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.db.models import Q

from pokes.models import Poke, User


class IndexView(generic.ListView):
  template_name = 'pokes/index.html'
  context_object_name = 'poke_list'

  def get_queryset(self):
    """
    Return all pokes not including pokes set in the future. Shows all
    """
    return Poke.objects.filter(
        poke_date__lte=timezone.now()
      ).order_by('-poke_date')

class NewUserView(generic.ListView):
  template_name = 'pokes/new_user.html'
  context_object_name = 'user_list'

  def get_queryset(self):
    """
    Return all users.
    """
    return User.objects.order_by('-username')

def add_user(request):
  username = request.POST['username'].strip()
  try:
    if not username:
      raise KeyError
    user = User.objects.filter(username__iexact=username)
    if not user:
      raise User.DoesNotExist
  except User.DoesNotExist:
    User.objects.create(username=username)
    return HttpResponseRedirect(reverse('pokes:index'))
  except KeyError:
    # Redisplay new user form.
    return render(request, 'pokes/new_user.html', {
      'error_message' : "Username must be provided.",
      'user_list' : User.objects.order_by('-username'),
    })
  else:
    # Redisplay new user form.
    return render(request, 'pokes/new_user.html', {
      'error_message' : "User already exists.",
      'user_list' : User.objects.order_by('-username'),
    })

# Convert to detail or list view?
def detail(request, user_id):
  user = get_object_or_404(User, pk=user_id)
  poke_list = Poke.objects.filter(
    Q(send_user__exact=user) | Q(receive_user__exact=user)).order_by('-poke_date')
  user_list = User.objects.exclude(username__exact=user.username).order_by('-username')
  return render(request, 'pokes/detail.html', {
    'user' : user,
    'poke_list' : poke_list,
    'user_list' : user_list})

def create_poke(request, user_id):
  sender_id = user_id
  receiver_id = request.POST['receiver']

  try:
    send_user = User.objects.get(id=sender_id)
    receive_user = User.objects.get(id=receiver_id)
  except ValueError:
    user = get_object_or_404(User, pk=sender_id)
    poke_list = Poke.objects.filter(
      Q(send_user__exact=user) | Q(receive_user__exact=user))
    user_list = User.objects.exclude(username__exact=user.username).order_by('-username')
    return render(request, 'pokes/detail.html', {
      'error_message' : "User not selected.",
      'user' : user,
      'poke_list' : poke_list,
      'user_list' : user_list})
  except User.DoesNotExist:
    user = get_object_or_404(User, pk=sender_id)
    poke_list = Poke.objects.filter(
      Q(send_user__exact=user) | Q(receive_user__exact=user))
    user_list = User.objects.exclude(username__exact=user.username).order_by('-username')
    return render(request, 'pokes/detail.html', {
      'error_message' : "Selected user does not exist.",
      'user' : user,
      'poke_list' : poke_list,
      'user_list' : user_list})
  else:
    time = timezone.now()
    Poke.objects.create(send_user=send_user,
                        receive_user=receive_user,
                        poke_date=time)
    return HttpResponseRedirect(reverse('pokes:index'))

django_poke/pokes/templates/pokes/detail.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'pokes/style.css' %}" />

<h1> {{ user.username }} </h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'pokes:create_poke' user.id %}" method="post">
  {% csrf_token %}
  <label for="receiver">Who would you like to poke? </label><br />
  <select name="receiver" id="receiver">
    <option value="">--</option>
    {% for receiver in user_list %}
      <option value="{{ receiver.id }}">{{ receiver.username }}</option>  
    {% endfor %}
  </select> 
  <input type="submit" value="Poke!" />
</form>

{% if poke_list %}
  <ul>
  {% for poke in poke_list %}
    <li><a href="{% url 'pokes:detail' poke.send_user.id%}">{{ poke.send_user.username }}</a> poked <a href="{% url 'pokes:detail' poke.receive_user.id%}">{{ poke.receive_user.username }}</a> at {{ poke.poke_date }}</li>
  {% endfor %}
  </ul>
{% else %}
    <p>No pokes for user.</p>
{% endif %}

django_poke/pokes/templates/pokes/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'pokes/style.css' %}" />

{% if poke_list %}
  <a href="{% url 'pokes:new_user'%}">Add user?</a>
    <ul>
    {% for poke in poke_list %}
        <li><a href="{% url 'pokes:detail' poke.send_user.id%}">{{ poke.send_user.username }}</a> poked <a href="{% url 'pokes:detail' poke.receive_user.id%}">{{ poke.receive_user.username }}</a> at {{ poke.poke_date }}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No pokes are available. <a href="{% url 'pokes:new_user'%}">Add user?</a></p>
{% endif %}

django_poke/pokes/templates/pokes/new_user.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'pokes/style.css' %}" />

<h1> Add User </h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'pokes:add_user' %}" method="post">
  {% csrf_token %}
  <label for="username">Username: </label>
  <input type="text" name="username" id="username" /><br />
  <input type="submit" value="Add user!">
</form>

{% if user_list %}
  <ul>
    {% for user in user_list %}
      <li><a href="{% url 'pokes:detail' user.id %}">{{ user.username }}</a>
    {% endfor %}
  </ul>
{% else %}
  <p>No users currently exist.</p>
{% endif %}